# Generated by Django 3.1.2 on 2020-10-13 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timedelta',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timedeltas', to='schedules.eventdefinition'),
        ),
        migrations.AlterField(
            model_name='timedelta',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timedeltas', to='schedules.schedule'),
        ),
    ]
