export const GET_SCHEDULES = "GET_SCHEDULES";
export const DELETE_SCHEDULE = "DELETE_SCHEDULE";
export const ADD_SCHEDULE = "ADD_SCHEDULE";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
